#!/bin/sh
set -e
maybe() {
    command -v "$1" > /dev/null && "$@"
}

if [ "$1" = 'startup' ]; then
    trap "trap - TERM && kill -- -$$" INT TERM EXIT

    # this is hell
    dbus-update-activation-environment --systemd \
        QT_QPA_PLATFORM WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

    maybe /usr/lib/x86_64-linux-gnu/libexec/kdeconnectd &
    maybe spectacle -s &
    maybe ~/.local/lib/pulseaudio-watch someblocks &
    null-notifyd &
    someblocks &
    swaybg -i ~/Pictures/spotlight.jpg -o '*' -m fit &
    somebar
else
    export QT_QPA_PLATFORM=wayland-egl
    export XDG_CURRENT_DESKTOP=wlroots
    exec dwl -s "setsid -w $0 startup"
fi
